<!-- <form role="form" method='post'>
    <div class="form-group">
        <?php// echo $this->form->email; ?>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-group">
        <label for="exampleInputFile">File input</label>
        <input type="file" id="exampleInputFile">
        <p class="help-block">Example block-level help text here.</p>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>
-->

<div class="span4 offset1">
    <h2>Enter some text to post...</h2>

<?php

    echo $this->form;   ?>
</div>

<div class="span4 offset1">
    <h2>All of your posts...</h2>

    <?php

    foreach($this->paginator as $post){
        echo '<p> Posted by '. $post->email .' : '. $post->postText  .'<a class="btn-small" href="'. $this->baseUrl('index/delete/id/'. $post->id); echo '">Obriši post</a></p>';
    }

    echo $this->paginationControl($this->paginator,
        'Sliding',
        'pagination.phtml');    ?>
</div>